shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps:
            - test: npm install && npm run functional
        environment:
            SD_API_HOST: beta.api.screwdriver.cd
            TEST_USERNAME: tk3fftk
            TEST_ORG: tk3fftk
        secrets:
            # Access key for functional tests
            - SD_API_TOKEN
            # Git access token
            - GIT_TOKEN

