---
auth:
    # A private key used for signing jwt tokens
    # Easily generate one by running
    # $ openssl genrsa -out jwt.pem 2048
    jwtPrivateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        YOUR-KEY-HERE
        -----END RSA PRIVATE KEY-----
    # The public key used for verifying the signature
    # Generate one by running
    # $ openssl rsa -in jwt.pem -pubout -out jwt.pub
    jwtPublicKey: |
        -----BEGIN PUBLIC KEY-----
        YOUR-KEY-HERE
        -----END PUBLIC KEY-----
    # The client id used for OAuth with github. Look up GitHub OAuth for details
    # https://developer.github.com/v3/oauth/
    oauthClientId: YOU-PROBABLY-WANT-SOMETHING-HERE
    # The client secret used for OAuth with github
    oauthClientSecret: AGAIN-SOMETHING-HERE-IS-USEFUL
    # A password used for encrypting session, and OAuth data.
    # **Needs to be minimum 32 characters**
    password: WOW-ANOTHER-INSECURE-PASSWORD!!!
    # A single access token used as an alternative to the Oauth login flow
    temporaryAccessKey: someAccessTokenThatIsTemporaryForUsingInTheMeantime
    # User name that is associated with the temporary access key
    temporaryAccessUser: quality_automation
    # A flag to set if the server is running over https.
    # Used as a flag for the OAuth flow
    https: false
    # Whitelist of users able to authenticate against the system
    # if empty, it allows everyone
    # @TODO remove this in the future
    whitelist:
        - FenrirUnbound
        - Filbird
        - cynthiax
        - d2lam
        - dvdizon
        - jer
        - minz1027
        - nicolaifsf
        - nkatzman
        - petey
        - sd-buildbot
        - shruthi-venkateswaran
        - stjohnjohnson
        - tkyi
    admins:
        - FenrirUnbound
        - Filbird
        - cynthiax
        - d2lam
        - dvdizon
        - jer
        - minz1027
        - nicolaifsf
        - nkatzman
        - petey
        - sd-buildbot
        - shruthi-venkateswaran
        - stjohnjohnson
        - tkyi

httpd:
    # Port to listen on
    port: 8080
    # Host to listen on (set to localhost to only accept connections from this machine)
    host: 0.0.0.0
    # Externally routable URI (usually your load balancer or CNAME)
    uri: http://localhost:8080
    # SSL Support
    tls: false
        # If you want SSL, you can easily add it by replacing `tls: false` with an object that
        # provides the options required by `tls.createServer`
        # https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener
        # key: |
        #     PRIVATE KEY HERE
        # cert: |
        #     YOUR CERT HERE

datastore:
    plugin: imdb
    imdb:
        # File to read/write the database to
        filename: ./database.json
    dynamodb:
        # Prefix to table names
        prefix: ""
        # AWS Access Key ID
        accessKeyId: WHAT-A-LEGITIMATE-LOOKING-KEY-ID
        # AWS Secret Access Key
        secretAccessKey: TOTALLY-REAL-LOOKING-AWS-KEYS

executor:
    plugin: k8s
    k8s:
        # The host or IP of the kubernetes cluster
        host: kubernetes
        # The jwt token used for authenticating kubernetes requests
        token: NOT-A-REAL-JWT-TOKEN
        # Launcher container tag to use
        launchVersion: latest
        # Log Service container tag to use
        logVersion: latest

scm:
    plugin: github

webhooks:
    github:
        # Secret to add to GitHub webhooks so that we can validate them
        secret: SUPER-SECRET-SIGNING-THING

logging:
    # Base URL for accessing logs
    baseUrl: https://s3-us-west-2.amazonaws.com/logs.screwdriver.cd

ecosystem:
    # URL for the User Interface
    ui: https://cd.screwdriver.cd
    # Badge service (needs to add a status and color)
    badges: https://img.shields.io/badge/build-{{status}}-{{color}}.svg
